SELECT
  DATE_TRUNC('month', ORDER_DATE) AS ORDER_MONTH,
  COUNT(*) AS ORDER_COUNT,
  SUM(LINE_AMOUNT) AS TOTAL_SALES
FROM {{ ref('stg_orders') }}
WHERE STATUS = 'completed'
  AND ORDER_DATE IS NOT NULL
GROUP BY DATE_TRUNC('month', ORDER_DATE)
