USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE DATABASE IF NOT EXISTS FIVETRAN_DB;
CREATE SCHEMA IF NOT EXISTS FIVETRAN_DB.RAW;

CREATE DATABASE IF NOT EXISTS ECOMMERCE_POC_DB;
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_POC_DB.MARTS;

SHOW SCHEMAS IN DATABASE FIVETRAN_DB;
SHOW SCHEMAS IN DATABASE ECOMMERCE_POC_DB;
