USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE ECOMMERCE_POC_DB;

SELECT CATEGORY, ORDER_COUNT, TOTAL_SALES
FROM MARTS.SALES_BY_CATEGORY
ORDER BY TOTAL_SALES DESC;

SELECT CUSTOMER_ID, CUSTOMER_NAME, ORDER_COUNT, TOTAL_SALES
FROM MARTS.ORDERS_PER_CUSTOMER
ORDER BY TOTAL_SALES DESC
LIMIT 10;

SELECT ORDER_MONTH, ORDER_COUNT, TOTAL_SALES
FROM MARTS.SALES_TREND
ORDER BY ORDER_MONTH;
