SELECT
  ORDER_ID,
  TRY_TO_DATE(ORDER_DATE) AS ORDER_DATE,
  TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
  NULLIF(TRIM(CUSTOMER_NAME), '') AS CUSTOMER_NAME,
  INITCAP(TRIM(CATEGORY)) AS CATEGORY,
  NULLIF(TRIM(PRODUCT), '') AS PRODUCT,
  QUANTITY,
  UNIT_PRICE,
  LOWER(TRIM(STATUS)) AS STATUS,
  QUANTITY * UNIT_PRICE AS LINE_AMOUNT
FROM {{ source('raw', 'orders') }}
WHERE ORDER_ID IS NOT NULL
